


# ned-path=HOME/raynet/simulations:HOME/raynet/simlibs/RLComponents/src:HOME/raynet/simlibs/ecmp/src:HOME/raynet/simlibs/RLCC/src:HOME/raynet/simlibs/rdp/src:HOME/inet4.5/src/inet:HOME/inet4.5/examples
ned-path=../../simulations:../../simlibs/RLComponents/src:../../simlibs/RLCC/src:../../../inet4.5/src/inet # :../../../inet4.5/src/inet/transportlayer/tcp #:../../../inet4.5/examples
check-signals = false
record-eventlog = false #true

[General]
network = simulations.RLSimulations.twoflows

sim-time-limit = 120s
# *.seed = 12345

**.minDelay = 4 ms #DELAY_PLACEHOLDER #${d=5..100 step 5} ms
**.linkrate = 96 Mbps # LINKRATE_PLACEHOLDER

#**.tcp.*.statistic-recording=true
# **.tcp.*.vector-recording=true
# **.orca_cntSignal.record = vector
**.vector-recording = true
#**.cli[*].tcp.conn-*.vector-recording=true
#**.*.ppp[*].queue.vector-recording=true
# **.tcp.*.vector-recording=true

# **.vector-recording = true
**.scalar-recording = false
**.bin-recording = false
**.statistic-recording = true #true

cmdenv-express-mode = false # false true

cmdenv-log-prefix = %l %J | #the prefix of a log statement line. Symbols in manual.

**.cmdenv-log-level = off
**.broker.cmdenv-log-level = off
**.stepper.cmdenv-log-level = off
**.cli[*].tcp.*.cmdenv-log-level = off
**.cli[*].tcp.*.cmdenv-log-level = off

**.srv[*].tcp.*.cmdenv-log-level = off
**.srv[*].app[*].*.cmdenv-log-level = off
**.srv[*].app[*].cmdenv-log-level = off

*.n = 1
# TCP Config
**.tcp.typename = "PacedTcp"
**.cli0.tcp.tcpAlgorithmClass = "Orca"
**.cli1.tcp.tcpAlgorithmClass = "TcpCubic"

# **.cli[1].tcp.tcpAlgorithmClass = "TcpCubic"
# **.srv[*].tcp.typename = "Tcp"
**.srv0.tcp.tcpAlgorithmClass =  "TcpCubic" # inet::tcp::TcpCubic"
**.tcp.mss= 1024
**.tcp.advertisedWindow = 1073741823
**.tcp.limitedTransmitEnabled = false # Need to add the limited transmit check for SACK based fadt recoverty.
**.tcp.windowScalingSupport = true
**.tcp.timestampSupport = true
**.cli0.tcp.initialSsthresh = 100*1024
**.cli1.tcp.initialSsthresh = 100*1024

**.tcp.nagleEnabled = true
**.tcp.sackSupport=true
**.tcp.delayedAcksEnabled = false
**.tcp.increasedIWEnabled = false
**.tcp.dupthresh = 3
**.tcp.max_burst = 100000
# **.tcp.conn.ackDelay = 50ms

# added by me
# **.tcp.conn.maxCwnd = 1000000



# tcp apps
**.cli0.numApps = 1
**.cli0.app[*].typename  = "TcpSessionApp"
**.cli0.app[*].active = true
**.cli0.app[*].localAddress = ""
**.cli0.app[*].localPort = -1 
**.cli0.app[*].connectAddress = "srv0"
**.cli0.app[*].connectPort = 80 

**.cli1.numApps = 1
**.cli1.app[*].typename  = "TcpSessionApp"
**.cli1.app[*].active = true
**.cli1.app[*].localAddress = ""
**.cli1.app[*].localPort = -1 
**.cli1.app[*].connectAddress = "srv0"
**.cli1.app[*].connectPort = 80 

**.srv0.numApps = 1
**.srv0.app[*].typename = "TcpSinkApp"
**.srv0.app[*].localAddress = ""
**.srv0.app[*].localPort = 80


**.cli0.app[0].tOpen = 0s
**.cli0.app[0].tSend = 0s
**.cli0.app[0].sendBytes = 1500MiB
**.cli0.app[0].tClose = 0s

**.cli1.app[0].tOpen = 0s
**.cli1.app[0].tSend = 0s
**.cli1.app[0].sendBytes = 1500MiB
**.cli1.app[0].tClose = 0s



# NIC configuration
**.ppp[*].queue.typename = "DropTailQueue" # in routers

# ADDED BY ME
# *.ppp[*].datarate = 100Gbps                # Set high bandwidth for all links
# *.ppp[*].delay = 1ms 
# *.ppp[*].queue.packetCapacity = 1000        # Increase queue capacity to handle more packets


**.r1.ppp[*].queue.packetCapacity = 500    #Q_PLACEHOLDER # ${b=100..1000 step 50}
#**.cli[*].ppp[*].queue.packetCapacity = 250
**.ppp[*].ppp.mtu = 1500B


